# Generated by Django 4.1.5 on 2023-01-17 09:12

from django.db import migrations, models
import movie.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=155)),
                ('description', models.TextField(blank=True, null=True)),
                ('average_movie_rate', models.FloatField()),
                ('date_of_birth', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to=movie.models.upload_news_image)),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actors',
            },
        ),
    ]
