# Generated by Django 4.1.5 on 2023-01-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='first_name',
            new_name='name',
        ),
    ]
